CREATE TABLE counters (
  entry_id INTEGER NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
  field TEXT NOT NULL,
  up INTEGER NOT NULL DEFAULT 0,
  down INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (entry_id, field)
) WITHOUT ROWID;
